export const ARTICLE_LIST_REQUEST = "ARTICLE_LIST_REQUEST";
export const ARTICLE_LIST_SUCCESS = "ARTICLE_LIST_SUCCESS";
export const ARTICLE_LIST_FAIL = "ARTICLE_LIST_FAIL";

export const ARTICLE_DISPLAY_REQUEST = "ARTICLE_DISPLAY_REQUEST";
export const ARTICLE_DISPLAY_SUCCESS = "ARTICLE_DISPLAY_SUCCESS";
export const ARTICLE_DISPLAY_FAIL = "ARTICLE_DISPLAY_FAIL";
