export const DD_UPDATE_REQUEST = "DD_UPDATE_REQUEST";
export const DD_UPDATE_SUCCESS = "DD_UPDATE_SUCCESS";
export const DD_UPDATE_FAIL = "DD_UPDATE_FAIL";

export const DD_CANCEL_REQUEST = "DD_CANCEL_REQUEST";
export const DD_CANCEL_SUCCESS = "DD_CANCEL_SUCCESS";
export const DD_CANCEL_FAIL = "DD_CANCEL_FAIL";
export const DD_CANCEL_CLEAR = "DD_CANCEL_CLEAR";

export const UPDATE_SUBSCRIPTION_REQUEST = "UPDATE_SUBSCRIPTION_REQUEST";
export const UPDATE_SUBSCRIPTION_SUCCESS = "UPDATE_SUBSCRIPTION_SUCCESS";
export const UPDATE_SUBSCRIPTION_FAIL = "UPDATE_SUBSCRIPTION_FAIL";

export const CREATE_DD_PAYMENT_REQUEST = "CREATE_DD_PAYMENT_REQUEST";
export const CREATE_DD_PAYMENT_SUCCESS = "CREATE_DD_PAYMENT_SUCCESS";
export const CREATE_DD_PAYMENT_FAIL = "CREATE_DD_PAYMENT_FAIL";
