export const EVENT_LIST_REQUEST = "EVENT_LIST_REQUEST";
export const EVENT_LIST_SUCCESS = "EVENT_LIST_SUCCESS";
export const EVENT_LIST_FAIL = "EVENT_LIST_FAIL";

export const EVENT_DISPLAY_REQUEST = "EVENT_DISPLAY_REQUEST";
export const EVENT_DISPLAY_SUCCESS = "EVENT_DISPLAY_SUCCESS";
export const EVENT_DISPLAY_FAIL = "EVENT_DISPLAY_FAIL";
