export const GRADING_DISPLAY_REQUEST = "GRADING_DISPLAY_REQUEST";
export const GRADING_DISPLAY_SUCCESS = "GRADING_DISPLAY_SUCCESS";
export const GRADING_DISPLAY_FAIL = "GRADING_DISPLAY_FAIL";

export const LIST_GRADING_RESULTS_REQUEST = "LIST_GRADING_RESULTS_REQUEST";
export const LIST_GRADING_RESULTS_SUCCESS = "LIST_GRADING_RESULTS_SUCCESS";
export const LIST_GRADING_RESULTS_FAIL = "LIST_GRADING_RESULTS_FAIL";
