export const LESSON_PLAN_LIST_REQUEST = "LESSON_PLAN_LIST_REQUEST";
export const LESSON_PLAN_LIST_SUCCESS = "LESSON_PLAN_LIST_SUCCESS";
export const LESSON_PLAN_LIST_FAIL = "LESSON_PLAN_LIST_FAIL";

export const LESSON_PLAN_DISPLAY_REQUEST = "LESSON_PLAN_DISPLAY_REQUEST";
export const LESSON_PLAN_DISPLAY_SUCCESS = "LESSON_PLAN_DISPLAY_SUCCESS";
export const LESSON_PLAN_DISPLAY_FAIL = "LESSON_PLAN_DISPLAY_FAIL";

export const LESSON_PLAN_DELETE_REQUEST = "LESSON_PLAN_DELETE_REQUEST";
export const LESSON_PLAN_DELETE_SUCCESS = "LESSON_PLAN_DELETE_SUCCESS";
export const LESSON_PLAN_DELETE_FAIL = "LESSON_PLAN_DELETE_FAIL";

export const LESSON_PLAN_UPDATE_REQUEST = "LESSON_PLAN_UPDATE_REQUEST";
export const LESSON_PLAN_UPDATE_SUCCESS = "LESSON_PLAN_UPDATE_SUCCESS";
export const LESSON_PLAN_UPDATE_FAIL = "LESSON_PLAN_UPDATE_FAIL";
export const LESSON_PLAN_UPDATE_RESET = "LESSON_PLAN_UPDATE_RESET";

export const LESSON_PLAN_CREATE_REQUEST = "LESSON_PLAN_CREATE_REQUEST";
export const LESSON_PLAN_CREATE_SUCCESS = "LESSON_PLAN_CREATE_SUCCESS";
export const LESSON_PLAN_CREATE_FAIL = "LESSON_PLAN_CREATE_FAIL";
export const LESSON_PLAN_CREATE_RESET = "LESSON_PLAN_CREATE_RESET";
