export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DISPLAY_REQUEST = "PRODUCT_DISPLAY_REQUEST";
export const PRODUCT_DISPLAY_SUCCESS = "PRODUCT_DISPLAY_SUCCESS";
export const PRODUCT_DISPLAY_FAIL = "PRODUCT_DISPLAY_FAIL";
