export const TRAINING_VIDEO_LIST_REQUEST = "TRAINING_VIDEO_LIST_REQUEST";
export const TRAINING_VIDEO_LIST_SUCCESS = "TRAINING_VIDEO_LIST_SUCCESS";
export const TRAINING_VIDEO_LIST_FAIL = "TRAINING_VIDEO_LIST_FAIL";

export const TRAINING_VIDEO_DISPLAY_REQUEST = "TRAINING_VIDEO_DISPLAY_REQUEST";
export const TRAINING_VIDEO_DISPLAY_SUCCESS = "TRAINING_VIDEO_DISPLAY_SUCCESS";
export const TRAINING_VIDEO_DISPLAY_FAIL = "TRAINING_VIDEO_DISPLAY_FAIL";
