export const TRAINING_SESSION_REQUEST = "TRAINING_SESSION_REQUEST";
export const TRAINING_SESSION_SUCCESS = "TRAINING_SESSION_SUCCESS";
export const TRAINING_SESSION_FAIL = "TRAINING_SESSION_FAIL";

export const MY_CLASS_LIST_REQUEST = "MY_CLASS_LIST_REQUEST";
export const MY_CLASS_LIST_SUCCESS = "MY_CLASS_LIST_SUCCESS";
export const MY_CLASS_LIST_FAIL = "MY_CLASS_LIST_FAIL";

export const MEMBER_CLASS_LIST_REQUEST = "MEMBER_CLASS_LIST_REQUEST";
export const MEMBER_CLASS_LIST_SUCCESS = "MEMBER_CLASS_LIST_SUCCESS";
export const MEMBER_CLASS_LIST_FAIL = "MEMBER_CLASS_LIST_FAIL";

export const ADD_CLASS_LIST_REQUEST = "ADD_CLASS_LIST_REQUEST";
export const ADD_CLASS_LIST_SUCCESS = "ADD_CLASS_LIST_SUCCESS";
export const ADD_CLASS_LIST_FAIL = "ADD_CLASS_LIST_FAIL";

export const DELETE_CLASS_LIST_REQUEST = "DELETE_CLASS_LIST_REQUEST";
export const DELETE_CLASS_LIST_SUCCESS = "DELETE_CLASS_LIST_SUCCESS";
export const DELETE_CLASS_LIST_FAIL = "DELETE_CLASS_LIST_FAIL";

export const SWITCH_CLASS_LIST_REQUEST = "SWITCH_CLASS_LIST_REQUEST";
export const SWITCH_CLASS_LIST_SUCCESS = "SWITCH_CLASS_LIST_SUCCESS";
export const SWITCH_CLASS_LIST_FAIL = "SWITCH_CLASS_LIST_FAIL";
