export const UPLOAD_IMG_REQUEST = "UPLOAD_IMG_REQUEST";
export const UPLOAD_IMG_SUCCESS = "UPLOAD_IMG_SUCCESS";
export const UPLOAD_IMG_FAIL = "UPLOAD_IMG_FAIL";
export const UPLOAD_IMG_CLEAR = "UPLOAD_IMG_CLEAR";
