export const UPLOAD_IMG_REQUEST = "UPLOAD_IMG_REQUEST";
export const UPLOAD_IMG_SUCCESS = "UPLOAD_IMG_SUCCESS";
export const UPLOAD_IMG_FAIL = "UPLOAD_IMG_FAIL";
export const UPLOAD_IMG_CLEAR = "UPLOAD_IMG_CLEAR";

export const UPLOAD_VIDEO_REQUEST = "UPLOAD_VIDEO_REQUEST";
export const UPLOAD_VIDEO_SUCCESS = "UPLOAD_VIDEO_SUCCESS";
export const UPLOAD_VIDEO_FAIL = "UPLOAD_VIDEO_FAIL";
export const UPLOAD_VIDEO_CLEAR = "UPLOAD_VIDEO_CLEAR";

export const UPLOAD_FILE_REQUEST = "UPLOAD_FILE_REQUEST";
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS";
export const UPLOAD_FILE_FAIL = "UPLOAD_FILE_FAIL";
export const UPLOAD_FILE_CLEAR = "UPLOAD_FILE_CLEAR";
